### ISSUE TITLE
Very new to Linux; A missing library?

### ISSUE THREAD

**Issue by JasonDKnight** [JuneStepp/OneLauncher#20]
There has been an error.
Error running /home/me/OneLauncher/build/OneLauncher : /home/me/OneLauncher/build/OneLauncher: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/me/OneLauncher/build/lib/libpython3.9.so.1.0)
The application will exit now.

Apologies in advance if this is a simple fix.  I am very new to the Linux world.

**Comment by JuneStepp** [comment]
A pre-release of 2.0 is out now that should resolve these issues. Linux builds are now compiled on Ubuntu 22.04 LTS, as per the minimum system requirements for Qt6.

https://github.com/JuneStepp/OneLauncher/releases/tag/v2.0.rc1
