### ISSUE TITLE
Documents folder isn't localized properly/wrongly resolved

### ISSUE THREAD

**Issue by Thaodan** [JuneStepp/OneLauncher#29]
Current situation:
Currently OneLauncher just assumes that XDG_DOCUMENTS_DIR is Documents while that's not always the case.
This in turn makes that the Lotro folder isn't properly found.

How it should be:
$XDG_CONFIG_HOME/user-dirs.dir should be resolved about the name of XDG_DOCUMENTS_DIR.

**Comment by JeremyStepp** [comment]
https://github.com/platformdirs/platformdirs/pull/39
