### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by DreamsUnderStars** [JuneStepp/OneLauncher#37]
Are you still working on this?

**Comment by JuneStepp** [comment]
Indeed! I've been working towards the 2.0 release. You can take a look at the [commits](https://github.com/JuneStepp/OneLauncher/commits/develop) if you want to know what's been added most recently. 
For the good while, I've been mainly working on a very large add-on manager refactor that hasn't gone online yet. Commits will speed up again after that until 2.0 releases.
