### ISSUE TITLE
SSLErrors because of wrong SSL standard

### ISSUE THREAD

**Issue by Thaodan** [JuneStepp/OneLauncher#44]
I try to run OneLauncher on OpenSUSE. I'm currently also packaging it. 
I noticed with your and my build that the launcher fails to connect with internal SSL error.

The issue looks similar too:
https://github.com/keenlabs/KeenClient-Python/issues/161

OneLauncher outputs:
```
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
MainWindow - WARNING - <urlopen error [SSL] internal error (_ssl.c:1002)>
MainWindow - ERROR - [E12] Error getting news
```

Trying curl as suggested in a similar bug shows:
```
curl --cacert certificates/ca_certs.pem --tls-max 1.0 --ciphers DEFAULT@SECLEVEL=1 https://gls.lotro.com  
curl: (35) OpenSSL/3.1.1: error:0A0000BF:SSL routines::no protocols available
```

**Comment by JuneStepp** [comment]
I'd highly recommend looking at the develop branch as the main branch is years behind and practically a different program code wise. The develop branch should work fine on Linux, main caveat being that I still make breaking changes occasionally with configs and such.  For the main branch there's a couple of things that need to be updated and tested to get it working properly again. I'm considering switching builds to the develop branch before the next major version is finished, anyway, though. If you want to discuss any of this, opening up a GitHub discussion would be great.

**Comment by JuneStepp** [comment]
Already fixed in https://github.com/junestepp/onelauncher/commit/76581bf3dcff8d98a560f8e8ac640d10cb17bc85.

**Comment by Thaodan** [comment]
I tried running the develop branch but it failed for similar reasons.

I didn't look any further as it not a stable release.

Just use devel but watch for breaking changes isn't a solution either.

I would recommend to accept my fix for the current version and make a
hotfix release till the next big version upgrade.
