### ISSUE TITLE
DDO stopped working

### ISSUE THREAD

**Issue by Crolug** [JuneStepp/OneLauncher#48]
`Initializing, please wait...
Available languages checked.
Fetched details from GLS data center.
World list obtained.
World queue configuration read.
[E12] Error getting news`

This shows up at first. And after hitting "Play" it adds also this:

`Checking account details...
[E15] SSL Error occurred in HTTPS connection`

**Comment by robertsimmons** [comment]
Same problem.

**Comment by Nightstar227** [comment]
Same problem as well, for the same 3 weeks. I kept hoping regular ddo updates would fix it, but alas that hasn't been the case. Hopefully we can get an update for this launcher.

**Comment by gtbX** [comment]
It looks like the certificate list included with OneLauncher is out-of-date or incomplete. As a workaround, I replaced it with a symlink to my system certificate list, and was able to launch the game again.

```sh
cd path/to/OneLauncher/build/certificates
mv cacerts.pem cacerts.pem.bak
# you may need to change /etc/ssl/certs/ca-certificates.crt to an appropriate file for your distro
ln -s /etc/ssl/certs/ca-certificates.crt ca_certs.pem
```

**Comment by Crolug** [comment]
> It looks like the certificate list included with OneLauncher is out-of-date or incomplete. As a workaround, I replaced it with a symlink to my system certificate list, and was able to launch the game again.
> 
> ```shell
> cd path/to/OneLauncher/build/certificates
> mv cacerts.pem cacerts.pem.bak
> # you may need to change /etc/ssl/certs/ca-certificates.crt to an appropriate file for your distro
> ln -s /etc/ssl/certs/ca-certificates.crt ca_certs.pem
> ```

The only problem is this workaround has no usage in Windows 11.

**Comment by SirL0LL0** [comment]
Same here, not working anymore. I also tried to rebuild the certificates chain but didn't work (i'm not an expert in SSH).

Please help, i love this launcher and don't want to use the official one.

**Comment by JuneStepp** [comment]
Hey! I'm finishing a fix right now. The plan is to release a pared-down version of 2.0 as soon as possible. These network issues have already long since been fixed there. I'll link a pre-release version for testing in this thread when it's ready.

Due to real life troubles, I haven't been able to work on OneLauncher these past few months, but I really appreciate your care for the project.

**Comment by Nightstar227** [comment]
This is great news for me, DDO has been unplayable for me since your launcher stopped working for me. I appreciate your work!

**Comment by JuneStepp** [comment]
Sorry for the wait. Pre-release is out now: https://github.com/JuneStepp/OneLauncher/releases/tag/v2.0.rc1

**Comment by Nightstar227** [comment]
This worked for me, great job, new launcher looks great and worked first
try.
