### ISSUE TITLE
setuptools missing from runtime dependencies

### ISSUE THREAD

**Issue by mcbeth** [JuneStepp/OneLauncher#50]
It looks like setuptools is missing from the runtime dependencies.
If I run the tool without it, after the wizard, the app fails to start when it tries to import `pkg_resources`.  Once I do add setuptools to the dependency list, I get the expected network failure (this was written during the great easter network outage)

**Comment by JuneStepp** [comment]
Thanks! Fixed in e68ddb2e459b18d7d9148971e93cd49774b1f9d9. Setuptools is no longer needed.

**Comment by mcbeth** [comment]
I can confirm that `setuptools` is no longer needed, but you do technically need `packaging` now

**Comment by JuneStepp** [comment]
`packaging` was already in use, but I've explicitly added it to the pyproject.toml now. For whatever reason, I thought it was part of the standard library.
