### ISSUE TITLE
Suggestion:  Allow multiboxing from OneLauncher

### ISSUE THREAD

**Issue by Git-Forked** [JuneStepp/OneLauncher#62]
The lotrolauncher allows multiboxing, and I think it would be a great feature if OneLauncher also did.

**Comment by JuneStepp** [comment]
Better multiboxing support is one of the main focuses for 2.1. It can currently be done with multiple OneLauncher instances, though.

**Comment by Git-Forked** [comment]
I look forward to seeing it available from a single launcher instance in the future.  Thank you.
