### ISSUE TITLE
Not finding Mordor world status

### ISSUE THREAD

**Issue by liamfrost** [JuneStepp/OneLauncher#63]
Issue trying to connect to the new EU server Mordor with the following error
![Screenshot 2024-08-03 204204](https://github.com/user-attachments/assets/f24ad4d6-487c-465c-a57e-1c28345c3e33)
 "Error fetching world status. You may want to check the news feed for a scheduled down time."

**Comment by JuneStepp** [comment]
Release with the fix is out: https://github.com/JuneStepp/OneLauncher/releases/tag/v2.0.1
