### ISSUE TITLE
Problem with Patching

### ISSUE THREAD

**Issue by BreadGar** [JuneStepp/OneLauncher#69]
It's the second patch that I do through One Launcher, and when the game launches, it says the game was not patched (I did see the progress in the console). and if I go to the original launcher, it starts up and crashes.  If I'm quick enough I can get to the repair, and do a full repair, and that fixes it.

But is there a problem with patching with One Launcher? Should I only patch through the default one?

**Comment by JuneStepp** [comment]
I've never heard of that happening before. Can you save the patching log and attach it here?

**Comment by BreadGar** [comment]
I'll do it next patch, unless it's saved somewhere?

**Comment by JuneStepp** [comment]
Are you on Linux of Windows?

**Comment by BreadGar** [comment]
> Are you on Linux of Windows?

On Windows

**Comment by JuneStepp** [comment]
Press Windows Key + R. This should open a dialog where you can type `%LOCALAPPDATA%`. Press enter and that will open a folder. Then open either `The Lord of the Rings Online` or `Dungeons and Dragons Online`. There should be two `.log` files in there.

**Comment by BreadGar** [comment]
I have this at the end of  TTEPatchClient.1.old
`//****************************************************************************************
// Filename: C:\Users\<NAME>\AppData\Local\The Lord of the Rings Online/TTEPatchClient.log
// Description: 
// Version: 3.0.2.2.RELEASE Portal:compiled Fri Mar 30 13:34:14 2018 : RELEASE
// Process ID: 5480 (0x1568)	Thread ID: 8776 (0x2248)
// Log Creation Time: Thu Aug 29 11:55:24 2024
// Current Time - System: Thu Aug 29 11:55:24 2024	Game: 000000000.000
// Times wrapped: 0	Writes: 0	Bytes Written: 0
//****************************************************************************************
000000000.000: creating datfile patch client
000000000.000: Trying to open D:\StandingStoneGames\The Lord of the Rings Online/client_general.dat...
000000000.000: SimpleDiskController::InitFile failed with PDISKERR error code [-2]
000000000.000: 

DiskCon::InitFile:
  datfile "client_general.dat" stamped with datpack versions eng:112, game:3,
  executable supporting datpack versions eng:-1, game: -1.

000000000.000: Falling back to read-only mode.
000000000.000: Successfully opened client_general.dat
000000000.000: Trying to open D:\StandingStoneGames\The Lord of the Rings Online/client_cell_1.dat...
000000000.000: 

DiskCon::InitFile:
  datfile "client_cell_1.dat" stamped with datpack versions eng:112, game:0,
  executable supporting datpack versions eng:-1, game: -1.

000000000.000: Successfully opened client_cell_1.dat
000000000.000: Trying to open D:\StandingStoneGames\The Lord of the Rings Online/client_map_15.dat...
000000000.000: 

DiskCon::InitFile:
  datfile "client_map_15.dat" stamped with datpack versions eng:112, game:0,
  executable supporting datpack versions eng:-1, game: -1.

000000000.000: Successfully opened client_map_15.dat
000000000.000: Trying to open D:\StandingStoneGames\The Lord of the Rings Online/client_cell_2.dat...`


And This in LotroLauncher_9.log
`2024.08.29 11:57:58[I]  Patcher::Initialize :  Licensee:  "Kevin Keaney" 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Licensed Products:  "Desktop" 
2024.08.29 11:57:58[W] LocaleManager::LocateLocalizedResource :  Failed to locate resource [ "ButtonFont.en-US.ttf" ]! 
2024.08.29 11:57:58[W] LocaleManager::LocateLocalizedResource :  Failed to locate resource [ "ButtonFont.en.ttf" ]! 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Current Locale Name:  "en_US" 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Current Language:     "English" 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Current Country:      "UnitedStates" 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Current BPC47 Name:   "en-US" 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Setting up RSS Feed Displayer... 
2024.08.29 11:57:58[I]  Patcher::Initialize :  Setting up Ad Viewer... 
2024.08.29 11:57:58[W] LocaleManager::LocateLocalizedResource :  Failed to locate resource [ "Launcher_en-US.qm" ]! 
2024.08.29 11:57:58[W] LocaleManager::LocateLocalizedResource :  Failed to locate resource [ "qt_en-US.qm" ]! 
2024.08.29 11:57:58[W] LocaleManager::LocateLocalizedResource :  Failed to locate resource [ "qt_en.qm" ]! 
2024.08.29 11:57:58[W] Data Center URL:   QUrl( "http://moria.gls.lotro.com/GLS.DataCenterServer/Service.asmx" )  
 
2024.08.29 11:57:58[W] LocaleManager::LocateLocalizedResource :  Failed to locate resource [ "splash_screen_en-US.bmp" ]! 
2024.08.29 11:57:58[I]  Patcher::changeEvent :  Retranslating the UI... 
2024.08.29 11:57:59[I]  Patcher::DoDownload :  Starting content download phase... 
2024.08.29 11:57:59[I]  Patcher::DoRawDownload :  Starting raw content download phase... 
2024.08.29 11:57:59[I]  NeedDirectXSetup :  Need DirectX setup?  false 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :  ---FileName:  "vcredist_x86.exe" 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :    product code found, so assume it's installed 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :  ---FileName:  "vcredist_x86.exe" 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :    product code found, so assume it's installed 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :  ---FileName:  "vcredist_x64.exe" 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :    product code found, so assume it's installed 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :  ---FileName:  "VC_redist.x86.exe" 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :      marker file exists, assume product is installed. 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :  ---FileName:  "VC_redist.x64.exe" 
2024.08.29 11:57:59[I]  RawDownloadFlow::RetrievePrereqs_Continue :      marker file exists, assume product is installed. 
2024.08.29 11:57:59[I]  Patcher::Go :  Start up the connection "thread" 
2024.08.29 11:58:00[I]  UserSettingsDialog::Initialize_DisplayAdapter :  Loaded D3D11.dll for Display Adapter Options! 
`

**Comment by BreadGar** [comment]
So it seemed to have worked properly today.

**Comment by BreadGar** [comment]
Seems fine with today's patch, Maybe I did something weird
