### ISSUE TITLE
OneLauncher does not close after game is shut down

### ISSUE THREAD

**Issue by salvoza** [JuneStepp/OneLauncher#70]
When I am finished playing DDO, the launcher stays open in this state

![onelauncher error - wont close](https://github.com/user-attachments/assets/c785063c-a755-437b-97c2-c85fda34ccba)

I am only able to close it via the Task Manager. I am using version 2.0.1

**Comment by JuneStepp** [comment]
I feel like I've seen this when something was wrong with my computer, but the specifics aren't coming to mind. Do you mind giving some more details like:
- Does this happen consistently? 
- Is this directly after exiting the game or was other stuff done like clicking a button or scrolling?

**Comment by JuneStepp** [comment]
Closing for now, but please respond to my previous comment if you're still having this issue.
